server:
  port: 8080

spring:
  datasource:
    username: root
    password: shendu.2020!
    url: jdbc:mysql://47.92.65.71:3306/sdpjw-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.po

#showSql
logging:
  level:
    com:
      example:
        mapper : debug